read input

diff --git a/.github/workflows/compatibilityCheck.yaml b/.github/workflows/compatibilityCheck.yaml
--- a/.github/workflows/compatibilityCheck.yaml
+++ b/.github/workflows/compatibilityCheck.yaml
@@ -29,43 +29,28 @@ jobs:
           - bigquery
           - cloudsql
           - config
-          - datastore
-          - firestore
-          - kms
-          - logging
-          - metrics
-          - multisample
-          - kotlin
-          - pubsub
-          - pubsub-bus
-          - pubsub-docs
-          - pubsub-emulator
-          - pubsub-integration
-          - secretmanager
-          - spanner
-          - storage
-          - trace
-          - vision
     steps:
       - name: Get current date
         id: date
         run: echo "::set-output name=date::$(date +'%Y-%m-%d' --utc)"
       - uses: actions/checkout@v2
+      - name: Read inputs
+        run: |
+          echo "repo: $REPO"
+          echo "deps: $DEPS"
+        env:
+          REPO: ${{ inputs.mavenRepository }}
+          DEPS: ${{ inputs.mavenDependencies }}
+      - name: Stop the job
+        run: |
+          # Fail
+          exit 1
+
       - name: Setup Java 11
         uses: actions/setup-java@v1
         if: matrix.it != 'native'
         with:
           java-version: 11
-      - name: Setup GraalVM
-        uses: DeLaGuardo/setup-graalvm@4.0
-        if: matrix.it == 'native' # note that this is no longer in the matrix
-        with:
-          graalvm: '21.2.0'
-          java: 'java11'
-          arch: 'amd64'
-      - name: Install GraalVM Native Image
-        if: matrix.it == 'native'
-        run: gu install native-image
       - uses: actions/cache@v2
         id: mvn-cache
         with:
