feat: error checks, branch name
* branch name is now date-based
* generation error check
* error check on generated libs

diff --git a/.github/workflows/generateAutoConfigs.yaml b/.github/workflows/generateAutoConfigs.yaml
--- a/.github/workflows/generateAutoConfigs.yaml
+++ b/.github/workflows/generateAutoConfigs.yaml
@@ -31,10 +31,8 @@ jobs:
         working-directory: spring-cloud-generator
         run: |
           set -x
-          SOURCE_BRANCH_NAME=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
-          NEW_BRANCH_NAME="generated-autoconfig--$SOURCE_BRANCH_NAME"
+          NEW_BRANCH_NAME="generated-autoconfig--$(date '+%Y%m%d%H%M%S')
           echo "NEW_BRANCH_NAME=$NEW_BRANCH_NAME" >> $GITHUB_OUTPUT
-          echo "SOURCE_BRANCH_NAME=$SOURCE_BRANCH_NAME" >> $GITHUB_OUTPUT
       - name: Generate library list
         continue-on-error: false
         working-directory: spring-cloud-generator
@@ -47,6 +45,26 @@ jobs:
         run: |
           set -x
           bash generate-all.sh
+      - name: Check for generation errors
+        continue-on-error: false
+        working-directory: spring-cloud-generator
+        run: |
+          set -x
+          has_errors=0
+          if [[ $(ls *failed-library-generations | wc -l) -eq 0 ]]; then
+            echo 'no errors at generation'
+            exit 0
+          fi
+          for failed_lib_name in $(find failed-library-generations -printf '%f\n' | tail -n+2); do
+            echo "***** FAILED TO GENERATE LIBRARY: $failed_lib_name"
+            cat failed-library-generations/$failed_lib_name
+          done
+          exit 1
+      - name: Check for compilation errors
+        continue-on-error: false
+        working-directory: spring-cloud-previews
+        run: |
+          mvn install -D checkstyle.skip
       - name: Detect changes
         id: detect_changes
         run: |
@@ -54,12 +72,16 @@ jobs:
           git add ./spring-cloud-previews
           CHANGED_FILES=`git diff --cached --numstat | wc -l | awk '{print $1}'`
           git reset -- ./spring-cloud-previews
+          echo "$CHANGED_FILES have changed after generation"
+          if [[ $CHANGED_FILES -eq 0 ]]; then
+            echo "PR will not be generated"
+          fi
           echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_OUTPUT
       - name: Generate PR
         if: steps.detect_changes.outputs.CHANGED_FILES > 0
         run: |
           set -x
-          MESSAGE=`echo "feat(generated): Generate new autoconfig libraries from $SOURCE_BRANCH_NAME"`
+          MESSAGE=`echo "feat(generated): Generate new autoconfig libraries"
           git stash push -- spring-cloud-previews/
           git reset --hard
           git remote update
@@ -79,5 +101,4 @@ jobs:
           fi
         env:
           NEW_BRANCH_NAME: ${{ steps.create_branch_names.outputs.NEW_BRANCH_NAME }}
-          SOURCE_BRANCH_NAME: ${{ steps.create_branch_names.outputs.SOURCE_BRANCH_NAME }}
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
